### ISSUE TITLE
This is not an issue but a doubt.

### ISSUE THREAD

**Issue by talentedandrew** [chapin666/kurento-group-call-node#1]
Why have you hosted the node app on 'https'?

**Comment by Cheng-Bin** [comment]
In chrome version 47+ they force you to use https to be allow using WebRTC API.  It work fine in Firefox.

**Comment by talentedandrew** [comment]
ok thanks....but can i change I use http instead of https?

**Comment by Cheng-Bin** [comment]
Oh, Sure.    my pleasure.

**Comment by talentedandrew** [comment]
@Cheng-Bin  , I cloned the SFU branch but its not working.I connect from two different systems in the same room but I dont see anyone else other than me.Where am I going wrong?
I'm using KMS 6.6.0 on Ubuntu 14.04 LTS (64 bits).Please help.
