### ISSUE TITLE
recording Room

### ISSUE THREAD

**Issue by SalvatoreAD** [chapin666/kurento-group-call-node#2]
Can you help me figure out how to record all the participants of the room?

Thanks

**Comment by Cheng-Bin** [comment]
Sorry,  Reply too late.

1. use composite
2. create RecorderEndpoint
3. hubPort.connect(recordPoint); 

Demo:  
https://github.com/TribeMedia/kurento-composite-conference-recording-nodejs
https://github.com/TribeMedia/kurento-composite-node-example

**Comment by cherishsantosh** [comment]
What about startRecording() and stopRecording(), Not able to find this function.
